/**
 * Created by Sahib Pandori on 3/28/2017.
 */

var addCommand = 'get';
var connectCommmand = 'connect';

var corrections = {

    'pattern block'   : addCommand + ' a turn block',
    'go to turn block': addCommand + ' a turn block',
    'get repeat block': addCommand + ' a repeat block',
    'connect block 200 block 1': connectCommmand + ' block 2 under block 1',
    'connect block 300 block 1': connectCommmand + ' block 3 under block 1',
    'connect block 400 block 1': connectCommmand + ' block 4 under block 1',
    'connect block 500 block 1': connectCommmand + ' block 5 under block 1',
    'connect block 600 block 1': connectCommmand + ' block 6 under block 1',
    'connect block 700 block 1': connectCommmand + ' block 7 under block 1',
    'connect block 800 block 1': connectCommmand + ' block 8 under block 1',
    'connect block 900 block 1': connectCommmand + ' block 9 under block 1',
    'connect block 100 block 2': connectCommmand + ' block 1 under block 2',
    'connect block 300 block 2': connectCommmand + ' block 3 under block 2',
    'connect block 400 block 2': connectCommmand + ' block 4 under block 2',
    'connect block 500 block 2': connectCommmand + ' block 5 under block 2',
    'connect block 600 block 2': connectCommmand + ' block 6 under block 2',
    'connect block 700 block 2': connectCommmand + ' block 7 under block 2',
    'connect block 800 block 2': connectCommmand + ' block 8 under block 2',
    'connect block 900 block 2': connectCommmand + ' block 9 under block 2',
    'connect block 100 block 3': connectCommmand + ' block 1 under block 3',
    'connect block 200 block 3': connectCommmand + ' block 2 under block 3',
    'connect block 400 block 3': connectCommmand + ' block 4 under block 3',
    'connect block 500 block 3': connectCommmand + ' block 5 under block 3',
    'connect block 600 block 3': connectCommmand + ' block 6 under block 3',
    'connect block 700 block 3': connectCommmand + ' block 7 under block 3',
    'connect block 800 block 3': connectCommmand + ' block 8 under block 3',
    'connect block 900 block 3': connectCommmand + ' block 9 under block 3',
    'connect block 100 block 4': connectCommmand + ' block 1 under block 4',
    'connect block 200 block 4': connectCommmand + ' block 2 under block 4',
    'connect block 300 block 4': connectCommmand + ' block 3 under block 4',
    'connect block 500 block 4': connectCommmand + ' block 5 under block 4',
    'connect block 600 block 4': connectCommmand + ' block 6 under block 4',
    'connect block 700 block 4': connectCommmand + ' block 7 under block 4',
    'connect block 800 block 4': connectCommmand + ' block 8 under block 4',
    'connect block 900 block 4': connectCommmand + ' block 9 under block 4',
    'connect block 100 block 5': connectCommmand + ' block 1 under block 5',
    'connect block 200 block 5': connectCommmand + ' block 2 under block 5',
    'connect block 300 block 5': connectCommmand + ' block 3 under block 5',
    'connect block 400 block 5': connectCommmand + ' block 4 under block 5',
    'connect block 600 block 5': connectCommmand + ' block 6 under block 5',
    'connect block 700 block 5': connectCommmand + ' block 7 under block 5',
    'connect block 800 block 5': connectCommmand + ' block 8 under block 5',
    'connect block 900 block 5': connectCommmand + ' block 9 under block 5',
    'connect block 100 block 6': connectCommmand + ' block 1 under block 6',
    'connect block 200 block 6': connectCommmand + ' block 2 under block 6',
    'connect block 300 block 6': connectCommmand + ' block 3 under block 6',
    'connect block 400 block 6': connectCommmand + ' block 4 under block 6',
    'connect block 500 block 6': connectCommmand + ' block 5 under block 6',
    'connect block 700 block 6': connectCommmand + ' block 7 under block 6',
    'connect block 800 block 6': connectCommmand + ' block 8 under block 6',
    'connect block 900 block 6': connectCommmand + ' block 9 under block 6',
    'connect block 100 block 7': connectCommmand + ' block 1 under block 7',
    'connect block 200 block 7': connectCommmand + ' block 2 under block 7',
    'connect block 300 block 7': connectCommmand + ' block 3 under block 7',
    'connect block 400 block 7': connectCommmand + ' block 4 under block 7',
    'connect block 500 block 7': connectCommmand + ' block 5 under block 7',
    'connect block 600 block 7': connectCommmand + ' block 6 under block 7',
    'connect block 800 block 7': connectCommmand + ' block 8 under block 7',
    'connect block 900 block 7': connectCommmand + ' block 9 under block 7',
    'connect block 100 block 8': connectCommmand + ' block 1 under block 8',
    'connect block 200 block 8': connectCommmand + ' block 2 under block 8',
    'connect block 300 block 8': connectCommmand + ' block 3 under block 8',
    'connect block 400 block 8': connectCommmand + ' block 4 under block 8',
    'connect block 500 block 8': connectCommmand + ' block 5 under block 8',
    'connect block 600 block 8': connectCommmand + ' block 6 under block 8',
    'connect block 700 block 8': connectCommmand + ' block 7 under block 8',
    'connect block 900 block 8': connectCommmand + ' block 9 under block 8',
    'connect block 100 block 9': connectCommmand + ' block 1 under block 9',
    'connect block 200 block 9': connectCommmand + ' block 2 under block 9',
    'connect block 300 block 9': connectCommmand + ' block 3 under block 9',
    'connect block 400 block 9': connectCommmand + ' block 4 under block 9',
    'connect block 500 block 9': connectCommmand + ' block 5 under block 9',
    'connect block 600 block 9': connectCommmand + ' block 6 under block 9',
    'connect block 700 block 9': connectCommmand + ' block 7 under block 9',
    'connect block 800 block 9': connectCommmand + ' block 8 under block 9'
};